import streamlit as st
import geopandas as gpd
import folium
from streamlit_folium import st_folium
import matplotlib.pyplot as plt
import os

# --- 1. PAGE CONFIG ---
st.set_page_config(page_title="Putnam County RCRA Siting", layout="wide")

st.title("Siting the Future: RCRA Landfill Suitability")
st.write("""
This interactive model identifies viable locations for solid waste facilities based on strict environmental and zoning criteria. 
The highlighted parcels possess **>30% compact clay** at a depth of at least 5 feet, sit above a **safe groundwater table** (>10ft deep), and strictly adhere to a **1,000-foot residential exclusion buffer**.
""")

# --- 2. LOAD THE DATA (Relative Paths) ---
@st.cache_data 
def load_data():
    # Relative path: looks in the same folder as app.py
    file_path = "putnam_suitability.geojson" 
    
    if os.path.exists(file_path):
        gdf = gpd.read_file(file_path)
        
        # Convert Timestamps to strings for JSON serialization
        for col in gdf.columns:
            if gdf[col].dtype.name.startswith('datetime'):
                gdf[col] = gdf[col].astype(str)
        return gdf
    return None

candidates = load_data()

# --- 3. BUILD THE INTERACTIVE MAP ---
if candidates is not None and not candidates.empty:
    # Center map on Putnam County
    m = folium.Map(location=[36.1627, -85.5016], zoom_start=11, tiles="cartodbpositron")

    # Define the styling
    def style_function(feature):
        return {
            'fillColor': '#006400', # Dark Green
            'color': 'black',
            'weight': 1,
            'fillOpacity': 0.7,
        }

    # Add the GeoJSON to the map
    folium.GeoJson(
        candidates,
        name="Candidate Sites",
        style_function=style_function,
        tooltip=folium.GeoJsonTooltip(
            fields=['MUKEY'], 
            aliases=['Soil Map Unit Key:'],
            localize=True
        )
    ).add_to(m)

    # Load and add the Flow Network Image Overlay
    # Relative path: looks in the same folder as app.py
    try:
        img_data = plt.imread("flow_network.png")
        # Bounds must stay exactly as generated by your Jupyter script
        bounds = [[34.99944444283109, -86.00055555599346], [37.00055555609492, -84.99944444380537]]
        
        folium.raster_layers.ImageOverlay(
            image=img_data,
            bounds=bounds,
            opacity=1.0,
            name="Surface Flow Network"
        ).add_to(m)
    except FileNotFoundError:
        st.warning("Surface Flow Network image not found. Ensure flow_network.png is in the GitHub repo.")

    # Add Layer Control to toggle layers
    folium.LayerControl(position='topleft').add_to(m)

    # FINAL RENDER
    st_folium(m, width=900, height=600)

    # --- 4. METHODOLOGY SIDEBAR ---
    st.sidebar.header("Suitability Criteria")
    st.sidebar.markdown("""
    * **Soil Profile:** >30% Clay at 5ft (SSURGO)
    * **Hydrology:** >10ft Depth to Water (TDEC)
    * **Zoning:** 1,000-Foot Buffer (County Assessor)
    """)

else:
    st.error("GeoJSON not found. Please ensure 'putnam_suitability.geojson' is uploaded to your GitHub repository.")
